### ISSUE TITLE
Extraction for edge

### ISSUE THREAD

**Issue by rik-ing** [y-zumi/processing-python#19]
#18

**Comment by rik-ing** [comment]
Edgeを抽出したあとどのように数値化しようか迷ったんですが、ヒストグラムを用いて画素数を取ろうかなと思ったんですが、どうでしょう？？

**Comment by y-zumi** [comment]
どんな数値になるかよくわかんないのでサンプルデータあればみしてくださいー

**Comment by rik-ing** [comment]
[このサイトを参照⭐️](https://algorithm.joho.info/programming/python/opencv-histgram-py/)

**Comment by rik-ing** [comment]
Edge抽出した線の密度で判断しようと思ったんだけど、やり方分からなくて諦めた

**Comment by y-zumi** [comment]
良くわかんないけど，画像とパラメータが１対１の関係になるように抽出してください．
座標にプロットする際に，エッジパラメータが１画像につき複数ある場合は，座標の指定ができないので

**Comment by rik-ing** [comment]
う〜〜んっ
こんな感じでEdgeが複数取られたらいけないということ？？？
<img width="302" alt="2017-12-31 19 12 55" src="https://user-images.githubusercontent.com/33277130/34460861-a7824212-ee5e-11e7-8589-344ff62c478d.png">

**Comment by y-zumi** [comment]
複数とった結果を一つの値で表現しないとプロット出来んでしょ

**Comment by rik-ing** [comment]
なるほどね！ 了解

**Comment by rik-ing** [comment]
エッジで取得した画像に対してCorenerの値をとりました！

出力画像
<img width="494" alt="2017-12-31 22 55 45" src="https://user-images.githubusercontent.com/33277130/34462035-e6c79f20-ee7d-11e7-9945-d30300b48508.png">

Cornerの数
<img width="384" alt="2017-12-31 22 56 08" src="https://user-images.githubusercontent.com/33277130/34462037-f6568276-ee7d-11e7-92aa-0a74a7791c63.png">

**Comment by rik-ing** [comment]
あとは、プログラムを複数の画像ver に書き換えるだけです。

**Comment by y-zumi** [comment]
ウニとたわしの数値と結構違う？
違うなら文句なしだけど

**Comment by rik-ing** [comment]
いい感じに数値違うよ
